# Account Microservice

server:
  port: 8072

spring:
  application:
    name: "account"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: Es7585**
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/alinedb"
    initialization-mode: always

app:
  security:
    secret-key: "r5u8x/A?D(G+KaPdSgVkYp3s6v9y$B&E"
    jwt:
      secret-key: "a37c1ab3-2744-4407-92ca-acb87a3ea5ec"
